server:
  port: 8011

spring:
  application:
    name: products
  ai:
    mcp:
      server:
        enabled: true
        type: ASYNC
        annotation-scanner:
          enabled: true  # Enable/disable annotation scanning

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mcpdb
    username: sa
    password: root