spring:
  application:
    name: multishell

  ai:
    ollama:
      base-url: http://localhost:11434   # URL por defecto de Ollama
      chat:
        options:
          model: qwen2.5:14b
          temperature: 0.1
          numCtx: 8192


  web:
    resources:
      static-locations: file:./../../chat-ui