spring:
  application:
    name: shell

  ai:
    ollama:
      enabled: true
      base-url: http://localhost:11434   # URL por defecto de Ollama
      chat:
        options:
          # model: llama3.1:8b
          model: qwen2.5:14b

    # --- groq / openai ---
    openai:
      enabled: false
      base-url: ${GROQ_API_URL:https://api.groq.com/openai/v1}
      api-key: ${GROQ_API_KEY:null}
      chat:
        options:
          model: ${GROQ_API_MODEL:null}
          temperature: 0.1
        extra-body:
          # GROQ
          include_reasoning: false
          # open ai
          # reasoning_effort: "none"

    mcp:
      client:
        name: mcp-shell-client
        type: ASYNC
        sse:
          connections:
            stores:
              url: http://localhost:8010
            products:
              url: http://localhost:8011
            stocks:
              url: http://localhost:8012


  web:
    resources:
      static-locations: file:./../../chat-ui